<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c78feb3e-53e6-4751-a500-f095264c71e0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="PhoneBook.Utils\**" />
    <Content Remove="PhoneBook.Utils\**" />
    <EmbeddedResource Remove="PhoneBook.Utils\**" />
    <None Remove="PhoneBook.Utils\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.7" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PhoneBook.Data\PhoneBook.Data.csproj" />
    <ProjectReference Include="..\PhoneBook.Services\PhoneBook.Services.csproj" />
    <ProjectReference Include="..\PhoneBook.Utils\PhoneBook.Utils.csproj" />
  </ItemGroup>

</Project>
